# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - run: |
        cd My-React-Project-main
        npm i
        npm test
        
  #API
    - run: |
        cd My-React-Project-main
        docker build -t front .        
    - run: |
        cd API_mysql-main
        docker build -t api .
    - run: |
        docker pull mysql
        docker pull phpmyadmin
    - run: |
        cd My-React-Project-main
        docker-compose up build
        docker-compose down
    
